### ISSUE TITLE
Incorrect "architectures" declaration in library.properties

### ISSUE THREAD

**Issue by maxgerhardt** [adafruit/Adafruit_WavePlayer#3]
- Arduino board:  `adafruit_clue_nrf52840`
- Arduino IDE version (found in Arduino -> About Arduino menu):  Not applicable, using PlatformIO core 6.1.7a2, Nordic nRF52 platform 9.4.0, `framework-arduinoadafruitnrf52` version 1.3.0

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

Trying to compile a semantically empty sketch using the Adafruit_Arcada.h libraries with
```cpp
#include <Arduino.h>
#include <Adafruit_Arcada.h>

void setup(){}
void loop(){}
```
in PlatformIO fails due to a the library dependency finder rejecting to include the therefore needed `Adafruit_WavePlayer` in this repository (hard dependency [here](https://github.com/adafruit/Adafruit_Arcada/blob/eaeaefa4d1abfb8df789b8e4bd82066cdd796eeb/arcadatype.h#L7)) only declares compatibility with the SAMD architecture

https://github.com/adafruit/Adafruit_WavePlayer/blob/6dec4dfefc8c310ff3ea7bff416abcf38ad112f0/library.properties#L8-L9

and we're compiling fo a nRF52 board. This library is however perfectly compilable for nRF52, and even ESP32 looking at the source code, so the `library.properties` is wrong.

In fact, your CI already does a build for ESP32 + nRF + SAMD.

The `library.properties` should be corrected to an appropriate `architectures` value (`*` or `samd,nRF5,esp32`?) to allow PlatformIO's library dependency finder to correctly identify and handle the library. (Same goes for the Arduino IDE I guess).

**Comment by ladyada** [comment]
thank you!  merged
